### ISSUE TITLE
Use in non-focus windows

### ISSUE THREAD

**Issue by jeffburton** [katebe/angular-presence#1]
I am using your directive as a timeout mechanism and it works great. Thanks for your work. I have one problem - I have the ability to pop open a new window from my application. It can start as a new tab - but the focus is still on the old window. The new window does not change states until I click on the tab and move the mouse over it. Then the timer starts. 

What can I do to make the timer start even if I never visit the window?

**Comment by tibramo** [comment]
Thanks for your feedback, i'm glad that you like it. I tried reproducing the problem with example 1 (http://katebe.github.io/angular-presence/) with IE, Firefox and Chrome but it always says "Are you there?" when i switch (after waiting) to the new opened tab - so the timer started already before.

I'm not doing anything to delay the initial start of the timer, so it starts just after angularjs has parsed the directive.

Can you reproduce the problem with my example page? What browser do you use (mobile maybe?)?

**Comment by jeffburton** [comment]
My use of your directive may be unusual, and may be the source of the
problem. What I first do when the page loads is call init with a very long
timeout (because at the logon page, I don't want a timeout). When the
person logs in, I change INACTIVE.enter to the timeout I want.

What I ended up doing was modifying the directive to expose the changeState
method. I then call $presence.changeState(0) after I change INACTIVE.enter.
This fixed the problem.

I saw the problem in chrome, with the the chrome window.open setting to use
a new tab. Chrome's behavior in this case is to load the new tab, but not
switch focus to it.

I didn't try any other browser.

**Comment by tibramo** [comment]
Okay, you're doing things i didn't thought of and i guess that's somehow the source of the problem ;-). I don't think i can fix this directly, but i'm thinking about extending the directive. The reason for your workaround is that you want to "activate" the directive at a later time, when the user logged in - right? So i would extend the `init` method with a Boolean parameter that defines if the timer starts immediately (default) or not. Then, the `$presence` service gets a new method called `start` (maybe with an optional parameter for the initial state) that you can call any time later to start the timer.

What do you think about it?

**Comment by jeffburton** [comment]
Yes, that would match what I'm trying to do. You know, when I was looking
at my code today and reviewing your code, I had one of those moments "How
did this ever work????" Because I saw what I was doing was not really in
scope of what you had designed.

 I appreciate you being so responsive.

**Comment by tibramo** [comment]
Okay, you could give it a try:

> If you like, you can pass `$presence.init` the boolean value `true` as a second parameter, so the internal timer for changing states will not start immediately. Later, call `$presence.start()` to start it. Additionaly, you can check with `$presence.isActive()` whether the timer is already running or not.

**Comment by jeffburton** [comment]
Sorry it took me so long to get back to this. I just installed your latest
version and it works perfectly. Thanks!

**Comment by tibramo** [comment]
No problem, I'm happy that i could help you.
