### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by char0n** [katebe/angular-presence#3]
I noticed that triggering desktop notifications on Chrome 44.0.2403.130 m (64-bit) causes browser to trigger MouseMove event with x=0, y=0 movement. Never the less the event is triggered andangular-presence reacts accordingly.

This pull request https://github.com/katebe/angular-presence/pull/2 solves the problem by inspecting the mousemove event.

**Comment by tibramo** [comment]
Cool, thank you very much for reporting this and creating a pull request :)

**Comment by char0n** [comment]
No problem, I only modified angular-presence.js,  but not angular-presence.min.js and src/angular-presence.js.

**Comment by tibramo** [comment]
Everything up-to-date now :)

**Comment by tibramo** [comment]
@char0n Is there a reason for using event.originalEvent and not the event.movementX / event.movementY directly? If I'm not wrong, orinigalEvent is only available when jQuery is used (see #4 )

**Comment by char0n** [comment]
If I remember correctly, I couldn't find those properties on jquery event wrapper object; only on original event object.

Yes, I can confirm. jQuery event object doesn't contain those properties. I guess jquery optimizes them into pageX/Y, screenX/Y. By looking at those you cannot find out how much the mouse have moved (you would have to have previous mousemove event a compute the diference).

**Comment by tibramo** [comment]
Okay, thank you. I think i fixed it now by using event.originalEvent only when it is available, otherwise the event directly.

**Comment by char0n** [comment]
Event.sourceCapabilities.firesTouchEvents should solve this problem in more elegant way.

Resource: https://developers.google.com/web/updates/2015/10/inputdevicecapabilities?hl=en
